source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'BonusFeed' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'RealmSwift'
end
